# cloudbuild.yaml (Đã sửa cho region australia-southeast2)
steps:
# Bước 1: Build Docker container từ thư mục athenaos-ai-service
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'australia-southeast2-docker.pkg.dev/${PROJECT_ID}/athena-repo/athena-ai-service:latest'
  - './athenaos-ai-service'

# Bước 2: Đẩy container đã build lên Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'australia-southeast2-docker.pkg.dev/${PROJECT_ID}/athena-repo/athena-ai-service:latest'

# Bước 3: Deploy container lên Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'athenaos-ai-service'
  - '--image=australia-southeast2-docker.pkg.dev/${PROJECT_ID}/athena-repo/athena-ai-service:latest'
  - '--region=australia-southeast2' # <-- ĐÃ SỬA
  - '--platform=managed'
  - '--allow-unauthenticated'

# Báo cho Cloud Build biết cần đẩy ảnh này sau khi build xong
images:
- 'australia-southeast2-docker.pkg.dev/${PROJECT_ID}/athena-repo/athena-ai-service:latest'